version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: school_attendance_db
    environment:
      POSTGRES_DB: school_attendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/03-seed.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d school_attendance']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
